# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.genros <- function(phi, theta, a1, a2, b, n1, n2, c) {
    .Call(`_medfateland_genros`, phi, theta, a1, a2, b, n1, n2, c)
}

.ellipseROS <- function(phi, theta, vws, ros) {
    .Call(`_medfateland_ellipseROS`, phi, theta, vws, ros)
}

.doubleEllipseROS <- function(phi, theta, vws, ros) {
    .Call(`_medfateland_doubleEllipseROS`, phi, theta, vws, ros)
}

.fireBrandFallingHeight <- function(initialHeight, timeFalling, Dp) {
    .Call(`_medfateland_fireBrandFallingHeight`, initialHeight, timeFalling, Dp)
}

.totalFirebrandLoftingTime <- function(z, z0, zF, Dp) {
    .Call(`_medfateland_totalFirebrandLoftingTime`, z, z0, zF, Dp)
}

.totalGasFlowPersistenceTime <- function(z, t0, zF) {
    .Call(`_medfateland_totalGasFlowPersistenceTime`, z, t0, zF)
}

.findFireBrandLoftedHeight <- function(t0, z0, zF, Dp) {
    .Call(`_medfateland_findFireBrandLoftedHeight`, t0, z0, zF, Dp)
}

.willBurnWhenHitFloor <- function(zIni, Dp) {
    .Call(`_medfateland_willBurnWhenHitFloor`, zIni, Dp)
}

.fireBrandBurningTimeFromCanopyStructure <- function(LAIc) {
    .Call(`_medfateland_fireBrandBurningTimeFromCanopyStructure`, LAIc)
}

.fireBrandFlameHeightFromCanopyStructure <- function(crownLength, LAIc) {
    .Call(`_medfateland_fireBrandFlameHeightFromCanopyStructure`, crownLength, LAIc)
}

drainageCells <- function(queenNeigh, waterQ, iCell) {
    .Call(`_medfateland_drainageCells`, queenNeigh, waterQ, iCell)
}

.getTrackSpeciesTranspiration <- function(trackSpecies, Eplant, x) {
    .Call(`_medfateland_getTrackSpeciesTranspiration`, trackSpecies, Eplant, x)
}

.getTrackSpeciesDDS <- function(trackSpecies, DDS, x) {
    .Call(`_medfateland_getTrackSpeciesDDS`, trackSpecies, DDS, x)
}

.copySnowpackToSoil <- function(y) {
    invisible(.Call(`_medfateland_copySnowpackToSoil`, y))
}

.tetisModifyKsat <- function(y, watershed_control, reverse) {
    invisible(.Call(`_medfateland_tetisModifyKsat`, y, watershed_control, reverse))
}

.copySnowpackFromSoil <- function(y) {
    invisible(.Call(`_medfateland_copySnowpackFromSoil`, y))
}

.copyStateFromResults <- function(y, localResults) {
    invisible(.Call(`_medfateland_copyStateFromResults`, y, localResults))
}

.tetisInterFlow <- function(y, waterO, queenNeigh, waterQ, watershed_control, patchsize) {
    .Call(`_medfateland_tetisInterFlow`, y, waterO, queenNeigh, waterQ, watershed_control, patchsize)
}

.tetisBaseFlow <- function(y, waterO, queenNeigh, waterQ, watershed_control, patchsize) {
    .Call(`_medfateland_tetisBaseFlow`, y, waterO, queenNeigh, waterQ, watershed_control, patchsize)
}

.tetisApplyBaseflowChangesToAquifer <- function(y, baseflowBalance, patchsize) {
    .Call(`_medfateland_tetisApplyBaseflowChangesToAquifer`, y, baseflowBalance, patchsize)
}

.tetisApplyLocalFlowsToAquifer <- function(y, CapillarityRise, DeepDrainage) {
    invisible(.Call(`_medfateland_tetisApplyLocalFlowsToAquifer`, y, CapillarityRise, DeepDrainage))
}

.tetisApplyDeepAquiferLossToAquifer <- function(y, watershed_control) {
    .Call(`_medfateland_tetisApplyDeepAquiferLossToAquifer`, y, watershed_control)
}

.tetisOverlandFlows <- function(Runoff, AquiferExfiltration, waterO, queenNeigh, waterQ) {
    .Call(`_medfateland_tetisOverlandFlows`, Runoff, AquiferExfiltration, waterO, queenNeigh, waterQ)
}

.tetisSimulationNonSoilCells <- function(y, tminVec, tmaxVec, precVec, radVec, waterO, queenNeigh, waterQ, watershed_control) {
    .Call(`_medfateland_tetisSimulationNonSoilCells`, y, tminVec, tmaxVec, precVec, radVec, waterO, queenNeigh, waterQ, watershed_control)
}

.initSerghei <- function(limits, nrow, ncol, sf2cell, xList, input_dir, output_dir) {
    .Call(`_medfateland_initSerghei`, limits, nrow, ncol, sf2cell, xList, input_dir, output_dir)
}

.callSergheiDay <- function(lct, xList, gridMeteo, localResults, sf2cell, serghei_interface) {
    invisible(.Call(`_medfateland_callSergheiDay`, lct, xList, gridMeteo, localResults, sf2cell, serghei_interface))
}

