# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.genros <- function(phi, theta, a1, a2, b, n1, n2, c) {
    .Call(`_medfateland_genros`, phi, theta, a1, a2, b, n1, n2, c)
}

.ellipseROS <- function(phi, theta, vws, ros) {
    .Call(`_medfateland_ellipseROS`, phi, theta, vws, ros)
}

.doubleEllipseROS <- function(phi, theta, vws, ros) {
    .Call(`_medfateland_doubleEllipseROS`, phi, theta, vws, ros)
}

.fireBrandFallingHeight <- function(initialHeight, timeFalling, Dp) {
    .Call(`_medfateland_fireBrandFallingHeight`, initialHeight, timeFalling, Dp)
}

.totalFirebrandLoftingTime <- function(z, z0, zF, Dp) {
    .Call(`_medfateland_totalFirebrandLoftingTime`, z, z0, zF, Dp)
}

.totalGasFlowPersistenceTime <- function(z, t0, zF) {
    .Call(`_medfateland_totalGasFlowPersistenceTime`, z, t0, zF)
}

.findFireBrandLoftedHeight <- function(t0, z0, zF, Dp) {
    .Call(`_medfateland_findFireBrandLoftedHeight`, t0, z0, zF, Dp)
}

.willBurnWhenHitFloor <- function(zIni, Dp) {
    .Call(`_medfateland_willBurnWhenHitFloor`, zIni, Dp)
}

.fireBrandBurningTimeFromCanopyStructure <- function(LAIc) {
    .Call(`_medfateland_fireBrandBurningTimeFromCanopyStructure`, LAIc)
}

.fireBrandFlameHeightFromCanopyStructure <- function(crownLength, LAIc) {
    .Call(`_medfateland_fireBrandFlameHeightFromCanopyStructure`, crownLength, LAIc)
}

.initSerghei <- function(limits, nrow, ncol, sf2cell, xList, input_dir, output_dir) {
    .Call(`_medfateland_initSerghei`, limits, nrow, ncol, sf2cell, xList, input_dir, output_dir)
}

.callSergheiDay <- function(lct, xList, gridMeteo, localResults, sf2cell, serghei_interface) {
    invisible(.Call(`_medfateland_callSergheiDay`, lct, xList, gridMeteo, localResults, sf2cell, serghei_interface))
}

.finishSerghei <- function() {
    invisible(.Call(`_medfateland_finishSerghei`))
}

drainageCells <- function(queenNeigh, waterQ, iCell) {
    .Call(`_medfateland_drainageCells`, queenNeigh, waterQ, iCell)
}

.getTrackSpeciesTranspiration <- function(trackSpecies, Eplant, x) {
    .Call(`_medfateland_getTrackSpeciesTranspiration`, trackSpecies, Eplant, x)
}

.getTrackSpeciesDDS <- function(trackSpecies, DDS, x) {
    .Call(`_medfateland_getTrackSpeciesDDS`, trackSpecies, DDS, x)
}

.copySnowpackToSoil <- function(y) {
    invisible(.Call(`_medfateland_copySnowpackToSoil`, y))
}

.copySnowpackFromSoil <- function(y) {
    invisible(.Call(`_medfateland_copySnowpackFromSoil`, y))
}

.copyStateFromResults <- function(y, localResults) {
    invisible(.Call(`_medfateland_copyStateFromResults`, y, localResults))
}

.createDayOutput <- function(nX) {
    .Call(`_medfateland_createDayOutput`, nX)
}

.fcpp_landunit_day <- function(xi, model, date, internalCommunication) {
    .Call(`_medfateland_fcpp_landunit_day`, xi, model, date, internalCommunication)
}

.tetisModifyKsat <- function(y, watershed_control, reverse) {
    invisible(.Call(`_medfateland_tetisModifyKsat`, y, watershed_control, reverse))
}

.tetisInterFlow <- function(interflowInput, interflowOutput, interflowBalance, y, waterO, queenNeigh, waterQ, watershed_control, patchsize) {
    invisible(.Call(`_medfateland_tetisInterFlow`, interflowInput, interflowOutput, interflowBalance, y, waterO, queenNeigh, waterQ, watershed_control, patchsize))
}

.tetisBaseFlow <- function(baseflowInput, baseflowOutput, baseflowBalance, y, waterO, queenNeigh, waterQ, watershed_control, patchsize) {
    invisible(.Call(`_medfateland_tetisBaseFlow`, baseflowInput, baseflowOutput, baseflowBalance, y, waterO, queenNeigh, waterQ, watershed_control, patchsize))
}

.tetisApplyBaseflowChangesToAquifer <- function(AquiferExfiltration, y, baseflowBalance, patchsize) {
    invisible(.Call(`_medfateland_tetisApplyBaseflowChangesToAquifer`, AquiferExfiltration, y, baseflowBalance, patchsize))
}

.tetisApplyLocalFlowsToAquifer <- function(y, CapillarityRise, DeepDrainage) {
    invisible(.Call(`_medfateland_tetisApplyLocalFlowsToAquifer`, y, CapillarityRise, DeepDrainage))
}

.tetisApplyDeepAquiferLossToAquifer <- function(DeepAquiferLoss, y, watershed_control) {
    invisible(.Call(`_medfateland_tetisApplyDeepAquiferLossToAquifer`, DeepAquiferLoss, y, watershed_control))
}

.tetisOverlandFlows <- function(RunoffExport, Runoff, AquiferExfiltration, waterO, queenNeigh, waterQ) {
    invisible(.Call(`_medfateland_tetisOverlandFlows`, RunoffExport, Runoff, AquiferExfiltration, waterO, queenNeigh, waterQ))
}

.tetisSimulationNonSoilCells <- function(Rain, NetRain, Runoff, Infiltration, InfiltrationExcess, DeepDrainage, Snow, Snowmelt, Runon, WatershedExport, y, tminVec, tmaxVec, precVec, radVec, waterO, queenNeigh, waterQ, watershed_control) {
    invisible(.Call(`_medfateland_tetisSimulationNonSoilCells`, Rain, NetRain, Runoff, Infiltration, InfiltrationExcess, DeepDrainage, Snow, Snowmelt, Runon, WatershedExport, y, tminVec, tmaxVec, precVec, radVec, waterO, queenNeigh, waterQ, watershed_control))
}

.watershedDayTetis_inner <- function(output, internalCommunication, local_model, y, waterOrder, queenNeigh, waterQ, watershed_control, date, gridMeteo, latitude, parallelize, num_cores, chunk_size, patchsize) {
    invisible(.Call(`_medfateland_tetisWatershedDay_inner`, output, internalCommunication, local_model, y, waterOrder, queenNeigh, waterQ, watershed_control, date, gridMeteo, latitude, parallelize, num_cores, chunk_size, patchsize))
}

